export enum ErrorType {
  // 공통
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // auth
  KAKAO_LOGIN_FAILED = 'KAKAO_LOGIN_FAILED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',

  // couple
  COUPLE_NOT_FOUND = 'COUPLE_NOT_FOUND',
  ALREADY_IN_COUPLE = 'ALREADY_IN_COUPLE',
  INVALID_COUPLE_CODE = 'INVALID_COUPLE_CODE',
  CANNOT_USE_OWN_COUPLE_CODE = 'CANNOT_USE_OWN_COUPLE_CODE',

  // coupleItem
  COUPLE_ITEM_NOT_FOUND = 'COUPLE_ITEM_NOT_FOUND',

  // ecoVerification
  ECO_VERIFICATION_NOT_FOUND = 'ECO_VERIFICATION_NOT_FOUND',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',

  // item
  ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
  ALREADY_OWNED_ITEM = 'ALREADY_OWNED_ITEM',
  NOT_ENOUGH_POINTS = 'NOT_ENOUGH_POINTS',
  NOT_FOUND_DEFAULT_ITEM = 'NOT_FOUND_DEFAULT_ITEM',

  // member
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',

  // memberEcoVerification
  MEMBER_ECO_VERIFICATION_NOT_FOUND = 'MEMBER_ECO_VERIFICATION_NOT_FOUND',
  MEMBER_ECO_VERIFICATION_MISMATCH = 'MEMBER_ECO_VERIFICATION_MISMATCH',
  ALREADY_SUBMITTED_ECO_VERIFICATION_TODAY = 'ALREADY_SUBMITTED_ECO_VERIFICATION_TODAY',
  VISION_SERVICE_UNAVAILABLE = 'VISION_SERVICE_UNAVAILABLE',
  INVALID_VISION_RESPONSE = 'INVALID_VISION_RESPONSE',
  VISION_JSON_PARSE_ERROR = 'VISION_JSON_PARSE_ERROR',
  VISION_SCHEMA_MISMATCH = 'VISION_SCHEMA_MISMATCH',
  ALREADY_SUBMITTED_ECO_VERIFICATION_LINK = 'ALREADY_SUBMITTED_ECO_VERIFICATION_LINK',
  INVALID_ECO_REVIEW_REQUEST_STATUS = 'INVALID_ECO_REVIEW_REQUEST_STATUS',
  INVALID_ECO_ADD_LINK_STATUS = 'INVALID_ECO_ADD_LINK_STATUS',
}
